# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "ub" do |ub|

  ub.vm.box = "ubuntu/bionic64"
  ub.vm.box_check_update = false
  ub.vm.hostname = "ubuntu1804"
   
  ub.vm.network "forwarded_port", guest: 80, host: 8080,  auto_correct: true
  ub.vm.network "private_network", ip: "192.168.10.10"
  
  ub.disksize.size = "20GB"
  
  ub.vm.provider "virtualbox" do |vb|
  vb.name = "ubuntu1804"  
  vb.memory = "1024"
  end
  ub.vm.provision "shell", path: "./provision/apache2.sh"
end


config.vm.define "ce" do |ce|
  ce.vm.box = "centos/7"
  ce.vm.box_check_update = false
  ce.vm.hostname = "centos"
  ce.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: true
  ce.vm.network "private_network", ip: "192.168.10.16"

  
  ce.vm.provider "virtualbox" do |vb|
    vb.name = "centos"
    vb.memory = "1024"
    end
    ce.vm.provision "shell", path: "./provision/httpd.sh"
  end
end